import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const myCustomFont = localFont({
  src: "./fonts/Akira Expanded Demo.otf",
  variable: "--font-custom", 
  weight: "100 900",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "FizZer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myCustomFont.variable} ${myCustomFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
